---
- name: System packages
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items: 
  - python-pip
  - git

- name: Set up Bonjour/Zeroconf (avahi-daemon)
  apt: pkg=avahi-daemon state=installed update_cache=yes

- name: Set up Python avahi support
  apt: pkg=python-avahi state=installed update_cache=yes

- name: Install avahi-aliases
  pip: name=git+git://github.com/thepug/avahi-aliases.git

- name: Copy aliases file
  copy: src=default.aliases dest=/etc/avahi/aliases.d/default
#- name: Install avahi crontab
#  copy: src=avahi.cron dest=/etc/cron.d/avahi owner=root mode=0644

- name: Advertise site with Zeroconf
  template: src=httpd.service.j2 dest=/etc/avahi/services/httpd.service mode=0644 
  notify: 
    - restart avahi
  notify:
    - restart avahi-aliases

